### ISSUE TITLE
Pypi release for version 1.4

### ISSUE THREAD

**Issue by alecghica** [collective/collective.traceview#11]
Hi @stonor, can you please make a fresh PyPi release for versions 1.4?

I can confirm the code is stable and working fine as we using it in production for quite some time now. We have a custom egg made in our own Python egg repository but I think it would be great to have it released on PyPi too.

Also I would love to help in the release management on PyPi of this package! So if you consider it fit you can add us rights to do the release on PyPi for the following users:

* alecghica
* alin.voinea
* eea

Recently I also updated documentation and added the direct link from [TraceView's supported Python frameworks](http://docs.appneta.com/support-matrix#python-frameworks).

**Comment by stonor** [comment]
Hi,

Sounds great! I've added you on pypi, so please go ahead.

**Comment by alecghica** [comment]
@stonor great! Thx!

**Comment by alecghica** [comment]
PyPi release done: https://pypi.python.org/pypi/collective.traceview/1.4
